In [10]:
import numpy as np
from sklearn.decomposition import PCA

X = np.array([[-1, -1, 1], [-2, -1, 3], [-3, -2,2], [1, 1, 6], [2, 1, 1], [3, 2, 2]])
pca = PCA(n_components=2)
pca.fit(X)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)
print(pca.components_)
print(pca.transform(X)  )

[0.69514987 0.30350381]
[6.32227154 4.17749558]
[[-0.83042896 -0.54618274 -0.10987336]
 [-0.15387961  0.0353192   0.98745816]]
[[ 1.54142174 -1.36262683]
 [ 2.15210398  0.7661691 ]
 [ 3.63858904 -0.10272866]
 [-1.76116846  3.33754316]
 [-2.04223062 -1.75362726]
 [-3.52871568 -0.8847295 ]]


In [1]:
import numpy as np 
a = np.array([1, 2, 3, 4, 5], ndmin =  2)  
print (a)

[[1 2 3 4 5]]


In [2]:
import numpy as np 
a = np.array([[1,  2],  [3,  4]])  
print (a)


[[1 2]
 [3 4]]


In [4]:
import numpy as np

dt = np.dtype('i4')
print(dt)

int32


In [3]:
import numpy as np

array = np.arange(24)
print(array.ndim)

print(array.reshape(2, 3, 4).ndim)

1
3


In [4]:
import numpy as np  
 
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


In [6]:
import numpy as np  
 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
import numpy as np  
 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3, 2, 1) 
print (a)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [10]:
import numpy as np  
 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3, 2, 1, 1) 
print (a)

[[[[1]]

  [[2]]]


 [[[3]]

  [[4]]]


 [[[5]]

  [[6]]]]


In [16]:
import numpy as np

a = np.arange(12)
print(a)
print(a.shape)

print(a.reshape(12, 1))
print(a.reshape(1, 12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [17]:
import numpy as np 
 
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


In [18]:
import numpy as np 
 
x = np.array([1,2,3,4,5])  
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [25]:
import numpy as np 

a = np.empty([3, 2], dtype = int)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
x = np.zeros(3, dtype='3int8, float32, (2,3)float64')
# 3int8 表示的是结构体的第一个元素是包含 3 个int元素的
# float 就表示第二个元素只是单纯的一个float值
# (2,3)float64 表示的是第三个元素是（2，3）的形状的 float元素
print(x)
print(np.arange(3))

[([0, 0, 0], 0., [[0., 0., 0.], [0., 0., 0.]])
 ([0, 0, 0], 0., [[0., 0., 0.], [0., 0., 0.]])
 ([0, 0, 0], 0., [[0., 0., 0.], [0., 0., 0.]])]
[0 1 2]


In [37]:
x = np.zeros(3, dtype=[('age','int'), ('height','i8'), ('weight',float), ('width','float',(2,3))])
 
print(x)
print(x.dtype)
print(x.dtype.names)  # 访问字段
print('修改字段名称')
x.dtype.names=('age','height','weight','width_adjusted')   #修改字段名称
print(x.dtype.names)

[(0, 0, 0., [[0., 0., 0.], [0., 0., 0.]])
 (0, 0, 0., [[0., 0., 0.], [0., 0., 0.]])
 (0, 0, 0., [[0., 0., 0.], [0., 0., 0.]])]
[('age', '<i4'), ('height', '<i8'), ('weight', '<f8'), ('width', '<f8', (2, 3))]
('age', 'height', 'weight', 'width')
修改字段名称
('age', 'height', 'weight', 'width_adjusted')


In [40]:
x = np.zeros(3, dtype=[('age','int'), ('height','i8'), ('weight',float), ('width','float',(2,3))])

x[['age', 'weight']]

array([(0, 0.), (0, 0.), (0, 0.)],
      dtype={'names': ['age', 'weight'], 'formats': ['<i4', '<f8'], 'offsets': [0, 12], 'itemsize': 68})

In [41]:
import numpy as np
 
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [42]:
import numpy as np
 
# 默认为浮点数
x = np.ones(5) 
print(x)
 
# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


In [49]:
import numpy as np

x = np.ones([2, 3], dtype = int)
print(x)

y = np.zeros_like(x)
print(y)

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [50]:
import numpy as np

li = [1, 2, 3]
arr = np.asarray(li)
print(arr)

[1 2 3]


In [55]:
import numpy as np

li = [(1, 2, 3), (4, 5)]
arr = np.asarray(li)
print(arr)
print(arr[1][1])

[(1, 2, 3) (4, 5)]
5


C:\Users\86151\AppData\Local\Temp\ipykernel_2996\859323467.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asarray(li)


In [56]:
import numpy as np 
 
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [57]:
import numpy as np
 
x = np.arange(5)  
print (x)

[0 1 2 3 4]


In [60]:
import numpy as np
x = np.arange(10,20,11)  
print (x)

[10]


In [61]:
import numpy as np
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [64]:
import numpy as np
a = np.linspace(1,-1,10)
print(a)


[ 1.          0.77777778  0.55555556  0.33333333  0.11111111 -0.11111111
 -0.33333333 -0.55555556 -0.77777778 -1.        ]


In [65]:
import numpy as np
 
# 不包含终点
a = np.linspace(10, 20,  5, endpoint =  False)  
print(a)

# 包含终点
b = np.linspace(10, 20,  5, endpoint =  True)  
print(b)

[10. 12. 14. 16. 18.]
[10.  12.5 15.  17.5 20. ]


In [67]:
import numpy as np
a =np.linspace(1,10,11,retstep= True)
 
print(a)

(array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ]), 0.9)


In [69]:
import numpy as np

a = np.arange(14)
s = slice(2, 18, 2)
print(a[s])

[ 2  4  6  8 10 12]


In [71]:
import numpy as np

a = np.arange(14)
print(a[2: 17: 2])

[ 2  4  6  8 10 12]


In [74]:
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:][1][0])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
4


In [75]:
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


In [77]:
import numpy as np

a = np.arange(12).reshape(3, 4)

for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [79]:
import numpy as np

a = np.arange(12).reshape(3, 4)

for i in np.nditer(a):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,

In [81]:
import numpy as np

a = np.arange(12).reshape(3, 4)

for i in np.nditer(a.T):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,

In [83]:
import numpy as np
 
a = np.arange(9).reshape(3,3) 
print ('原始数组：')
for row in a:
    print (row)
 
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print ('迭代后的数组：')
for element in a.flat:
    print (element)
    
print(a)

原始数组：
[0 1 2]
[3 4 5]
[6 7 8]
迭代后的数组：
0
1
2
3
4
5
6
7
8
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [84]:
import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('获取数组中一个值：')
print(np.where(a==6))   
print(a[1,1,0])  # 为 6
print ('\n')
 
 
# 将轴 2 滚动到轴 0（宽度到深度）
 
print ('调用 rollaxis 函数：')
b = np.rollaxis(a,2,0)
print (b)
# 查看元素 a[1,1,0]，即 6 的坐标，变成 [0, 1, 1]
# 最后一个 0 移动到最前面
print(np.where(b==6))   
print ('\n')
 
# 将轴 2 滚动到轴 1：（宽度到高度）
 
print ('调用 rollaxis 函数：')
c = np.rollaxis(a,2,1)
print (c)
# 查看元素 a[1,1,0]，即 6 的坐标，变成 [1, 0, 1]
# 最后的 0 和 它前面的 1 对换位置
print(np.where(c==6))   
print ('\n')

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
获取数组中一个值：
(array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64))
6


调用 rollaxis 函数：
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
(array([0], dtype=int64), array([1], dtype=int64), array([1], dtype=int64))


调用 rollaxis 函数：
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))




In [85]:
import numpy as np
 
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])  
 
# 对 y 广播 x
b = np.broadcast(x,y)  
# 它拥有 iterator 属性，基于自身组件的迭代器元组
 
print ('对 y 广播 x：')
r,c = b.iters
 
# Python3.x 为 next(context) ，Python2.x 为 context.next()
print (next(r), next(c))
print (next(r), next(c))
print ('\n')
# shape 属性返回广播对象的形状
 
print ('广播对象的形状：')
print (b.shape)
print ('\n')
# 手动使用 broadcast 将 x 与 y 相加
b = np.broadcast(x,y)
c = np.empty(b.shape)
 
print ('手动使用 broadcast 将 x 与 y 相加：')
print (c.shape)
print ('\n')
c.flat = [u + v for (u,v) in b]
 
print ('调用 flat 函数：')
print (c)
print ('\n')
# 获得了和 NumPy 内建的广播支持相同的结果
 
print ('x 与 y 的和：')
print (x + y)

对 y 广播 x：
1 4
1 5


广播对象的形状：
(3, 3)


手动使用 broadcast 将 x 与 y 相加：
(3, 3)


调用 flat 函数：
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


x 与 y 的和：
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [86]:
import numpy as np 
 
a = np.arange(9, dtype = np.float_).reshape(3,3)  
print ('第一个数组：')
print (a)
print ('\n')
print ('第二个数组：')
b = np.array([10,10,10])  
print (b)
print ('\n')

print(a*b)

第一个数组：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


第二个数组：
[10 10 10]


[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


In [4]:
# 矩阵乘法
import numpy as np

X = np.array([[150, 1],[200, 1],[250, 1],[300, 1],[350, 1],[400, 1],[600, 1]])
print(X)

omega = np.zeros((2, 1))
print(omega)

z = X@omega
print(z)

[[150   1]
 [200   1]
 [250   1]
 [300   1]
 [350   1]
 [400   1]
 [600   1]]
[[0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [18]:
import random

m = 10

j = random.randint(0, m - 1)
print(j)

0


In [2]:
from sympy import Float 
Float(1.1)

1.10000000000000

In [5]:
from sympy import Rational

Rational(3/4)

3/4

In [8]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')
expr = x + 2*y**2
expr

x + 2*y**2

In [9]:
s=Symbol('side') 
s**3

side**3

In [10]:
from sympy import symbols
x, y, z = symbols('x y z')

In [11]:
from sympy.abc import x, y, z
x**2 + y**2 + z**2

x**2 + y**2 + z**2

In [15]:
from sympy import symbols
list_symbols = symbols('a:5')
print(list_symbols)
print(list_symbols[0])

(a0, a1, a2, a3, a4)
a0


In [19]:
from sympy import *

x = symbols('x')
a = symbols('a')
expr = sin(x)**2+cos(x)**2
expr

sin(x)**2 + cos(x)**2

In [20]:
expr.subs(x, a)

sin(a)**2 + cos(a)**2

In [21]:
expr.subs(x, 0)

1

In [22]:
from sympy.abc import a,b 

expr=(a+b)**2
expr1=expr.subs(b,a+b) 
expr1

(2*a + b)**2

In [25]:
from sympy import *

expr="x**2+3*x+2" 
expr1=sympify(expr)
expr1.subs(x,2)

12

In [27]:
from sympy import *
sympify("x***2")

SympifyError: Sympify of expression 'could not parse 'x***2'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)

In [28]:
sympify("10/5+4/2")

4

In [29]:
sympify("10/5+4/2", evaluate=False)

10/5 + 4/2

In [31]:
from sympy.abc import r 

expr=pi*r**2 
expr
expr.evalf(subs={r:5})

78.5398163397448

In [32]:
expr=a/b
expr.evalf(20, subs={a:10, b:3})

3.3333333333333333333

In [33]:
expr=1/sin(x)
f=lambdify(x, expr) 
f(3.14)

627.8831939138764

In [34]:
expr=a**2+b**2
f=lambdify([a,b],expr)
f(2,3)

13

In [36]:
f=lambdify([a,b],expr, "numpy")

import numpy 

l1=numpy.arange(1,6) 
l2=numpy.arange(6,11) 
f(l1,l2)

array([ 37,  53,  73,  97, 125])

In [41]:
from sympy import *

x = sympify(true)
x, S.true

(True, True)

In [42]:
from sympy import *

x = sympify(false)
x, S.false

(False, False)

In [44]:
from sympy import * 
from sympy.logic.boolalg import And

x,y=symbols('x y') 
x=True
y=True

And(x,y), x&y

(True, True)

In [45]:
from sympy import * 
from sympy.logic.boolalg import Or 

x,y=symbols('x y') 
x=True 
y=False 
Or(x,y), x|y

(True, True)

In [46]:
from sympy import * 
from sympy.logic.boolalg import Or, And, Not 

x,y=symbols('x y') 
x=True 
y=False

Not(x), Not(y)

(False, True)

In [49]:
from sympy import * 
from sympy.logic.boolalg import Xor 

x,y=symbols('x y') 
x=True 
y=False
Xor(x,y), x^y

(True, True)

In [50]:
from sympy import * 
from sympy.logic.boolalg import Nand 

a,b,c=symbols('a b c') 

a,b,c=(True, False, True) 

Nand(a,b,c), Nand(a,c)


(True, False)

In [51]:
from sympy import * 

from sympy.logic.boolalg import Nor 

a,b,c=symbols('a b c') 

a,b,c=(True, False, True) 

Nor(a,b,c), Nor(a,c)


(False, False)

In [52]:
from sympy import * 

from sympy.logic.boolalg import Equivalent 

a,b,c=symbols('a b c') 

a,b,c=(True, False, True) 

Equivalent(a,b), Equivalent(a,c)

(False, True)

In [53]:
from sympy import *
from sympy.logic.boolalg import ITE

a,b,c=symbols('a b c')
a,b,c=(True, False, True) 

ITE(a,b,c), ITE(a,c,b)

(False, True)

In [54]:
ask(Q.algebraic(pi))

False

In [55]:
from sympy import * 
x=Symbol('x')
expr=sin(x)**2 + cos(x)**2 
simplify(expr)

1

In [56]:
a,b=symbols('a b') 
expand((a+b)**2)

a**2 + 2*a*b + b**2

In [57]:
x,y,z=symbols('x y z') 
expr=(x**2*z + 4*x*y*z + 4*y**2*z) 
factor(expr)

z*(x + 2*y)**2

In [58]:
expr=x*y + x - 3 + 2*x**2 - z*x**2 + x**3
expr

x**3 - x**2*z + 2*x**2 + x*y + x - 3

In [59]:
collect(expr,x)

x**3 + x**2*(2 - z) + x*(y + 1) - 3

In [60]:
expr1=x**2+2*x+1 

expr2=x+1 

cancel(expr1/expr2)

x + 1

In [61]:
from sympy import trigsimp, sin, cos 
from sympy.abc import x, y

expr = 2*sin(x)**2 + 2*cos(x)**2 

trigsimp(expr)

2

In [62]:
expr=x**y*x**z*y**z
expr

x**y*x**z*y**z

In [63]:
powsimp(expr)

x**(y + z)*y**z

In [64]:
expr=factorial(x)/factorial(x - 3)
expr

factorial(x)/factorial(x - 3)

In [65]:
combsimp(expr)

x*(x - 2)*(x - 1)

In [66]:
logcombine(a*log(x) + log(y) - log(z))

a*log(x) + log(y) - log(z)

In [67]:
logcombine(a*log(x) + log(y) - log(z), force=True)

log(x**a*y/z)

In [68]:
from sympy import diff, sin, exp 
from sympy.abc import x,y
expr=x*sin(x*x)+1
expr

x*sin(x**2) + 1

In [69]:
diff(expr,x)

2*x**2*cos(x**2) + sin(x**2)

In [70]:
diff(x**4,x,3)

24*x

In [71]:
from sympy import Derivative 

d=Derivative(expr) 
d

Derivative(x*sin(x**2) + 1, x)

In [72]:
d.doit()

2*x**2*cos(x**2) + sin(x**2)

In [74]:
from sympy import *
x,y = symbols('x y') 
expr=x**2 + x + 1 
integrate(expr, x)

x**3/3 + x**2/2 + x

In [75]:
expr=exp(-x**2) 
integrate(expr,(x,0,oo) )

sqrt(pi)/2

In [77]:
expr=exp(-x**2 - y**2)
integrate(expr,(x,0,oo),(y,0,oo))

pi/4

In [78]:
expr = Integral(log(x)**2, x)
expr

Integral(log(x)**2, x)

In [79]:
expr.doit()

x*log(x)**2 - 2*x*log(x) + 2*x

In [80]:
from sympy import * 
re(5+3*I)

5

In [81]:
from sympy import * 
im(5+3*I)

3

In [87]:
sign(1.55), sign(-1), sign(S.Zero), sign(-I),sign(-1-I)

(1, -1, 0, -I, sign(-1 - I))

In [88]:
Abs(2+3*I)

sqrt(13)

In [89]:
conjugate(4+7*I)

4 - 7*I

In [90]:
ceiling(pi), ceiling(Rational(20,3)), ceiling(2.6+3.3*I)

(4, 7, 3 + 4*I)

In [91]:
floor(pi), floor(Rational(100,6)), floor(6.3-5.9*I)

(3, 16, 6 - 6*I)

In [92]:
frac(3.99), frac(Rational(10,3)), frac(10)

(0.990000000000000, 1/3, 0)

In [93]:
x=Symbol('x') 
factorial(x)

factorial(x)

In [94]:
x,y=symbols('x y') 
binomial(x,y)

binomial(x, y)

In [95]:
from sympy import * 
x,y=symbols('x y') 
Eq(x, y)

Eq(x, y)

In [96]:
solveset(exp(x),x)

EmptySet

In [97]:
from sympy import * 
x,y=symbols('x y')
linsolve([Eq(x-y,4),Eq( x + y ,1) ], (x, y))

{(5/2, -3/2)}

In [98]:
a,b=symbols('a b') 
a=Matrix([[1,-1],[1,1]])
b=Matrix([4,1])
linsolve([a,b], (x,y))

{(5/2, -3/2)}

In [99]:
a,b=symbols('a b') 
nonlinsolve([a**2 + a, a - b], [a, b])

{(-1, -1), (0, 0)}

In [100]:
x=Symbol('x') 
f=symbols('f', cls=Function)
f(x)

f(x)

In [101]:
f(x).diff(x)

Derivative(f(x), x)

In [102]:
eqn=Eq(f(x).diff(x)-f(x), sin(x)) 
eqn

Eq(-f(x) + Derivative(f(x), x), sin(x))

In [103]:
dsolve(eqn, f(x))

Eq(f(x), C1*exp(x) - sin(x)/2 - cos(x)/2)

In [109]:
from sympy import *

m = 10
omega_vec = []
for i in range(m):
    omega = symbols('omega' + str(i))
    omega_vec.append(omega)
    
print()

NameError: name 'np' is not defined

In [6]:
import numpy as np
arr = np.ones(10)*2
arr = np.square(arr)
sum(arr)

40.0